import React, { createContext, useContext, useState, useEffect } from 'react'
import { logTranslationValidation } from '../utils/translationValidator'

// Create context
const LanguageContext = createContext()

// Language hook
export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

// Language provider component
export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Get saved language from localStorage or default to English
    const savedLanguage = localStorage.getItem('language')
    return savedLanguage || 'en'
  })

  // Save language preference to localStorage
  useEffect(() => {
    localStorage.setItem('language', language)
  }, [language])

  // Translation function
  const t = (key) => {
    const translations = {
      en: {
        // Navigation
        'nav.home': 'Home',
        'nav.about': 'About',
        'nav.menu': 'Menu',
        'nav.gallery': 'Gallery',
        'nav.storeLocator': 'Store Locator',
        'nav.reviews': 'Reviews',
        'nav.contact': 'Contact',
        
        // Home Page
        'home.hero.title': 'Fresh Sugarcane Juice',
        'home.hero.subtitle': 'From the Heart of Zanzibar',
        'home.hero.description': 'Experience the authentic taste of pure, fresh sugarcane juice - naturally sweet, refreshing, and full of nutrients.',
        'home.hero.cta': 'Order Now',
        'home.hero.cta2': 'View Menu',
        
        'home.about.title': 'About Utamu wa Miwa',
        'home.about.description': 'We bring you the freshest sugarcane juice, pressed daily from locally grown sugarcane. Our traditional methods ensure maximum freshness and natural sweetness.',
        'home.about.cta': 'Learn More',
        'home.cta.description': 'Order now on WhatsApp and we\'ll have your fresh juice ready for you!',
        'home.cta.button': 'Chat on WhatsApp',
        
        'home.stats.customers': 'Happy Customers',
        'home.stats.flavors': 'Unique Flavors',
        'home.stats.years': 'Years of Excellence',
        'home.stats.daily': 'Fresh Daily',
        
        'home.menu.title': 'Our Menu',
        
        // Why Us Section
        'home.whyUs.title': 'Why Us?',
        'home.whyUs.subtitle': 'What Makes Us Special',
        'home.whyUs.fresh.title': '100% Fresh',
        'home.whyUs.fresh.desc': 'Pressed fresh in front of you — no preservatives, no artificial flavors.',
        'home.whyUs.local.title': 'Local Sugarcane',
        'home.whyUs.local.desc': 'Sourced directly from local Zanzibari farmers for maximum freshness.',
        'home.whyUs.energy.title': 'Natural Energy',
        'home.whyUs.energy.desc': 'The perfect natural energy boost — pure cane sugar, no caffeine.',
        'home.whyUs.love.title': 'Made with Love',
        'home.whyUs.love.desc': 'Every cup prepared with passion and care by our local team.',
        'home.cta.title': 'Ready for a Refreshing Sip?',
        'home.viewFullMenu': 'View Full Menu',
        'home.reviews.title': 'Reviews',
        'home.reviews.subtitle': 'What Our Customers Say',
        'customer.name': 'bin abass',
        'about.title': 'Born from the Heart of Zanzibar',
        'about.description': 'Utamu wa Miwa started as a small street vendor in Stone Town, Zanzibar. With fresh sugarcane sourced directly from local farms, we press every cup by hand — delivering the pure, natural taste that Zanzibaris have loved for generations.',
        'header.tagline': 'Fresh from farm to glass',
        'nav.more': 'More',
        'menu.customOrders': 'Custom orders welcome!',
        'menu.customOrdersDesc': 'Want a special blend? Contact us on WhatsApp',
        'menu.addons': 'Add-ons',
        'menu.addons.desc': 'Enhance your drink with these extras',
        
        // Products
        'product.classic': 'Classic Sugarcane Juice',
        'product.ginger': 'Ginger Sugarcane Blend',
        'product.lemon': 'Lemon Sugarcane Twist',
        'product.mint': 'Mint Sugarcane Twist',
        'product.passion': 'Passion Fruit',
        'product.cucumber': 'Cucumber Sugarcane Twist',
        'product.extraIce': 'Extra Ice',
        'product.extraIce.desc': 'Fresh ice cubes for extra refreshment',
        
        'product.classic.desc': 'Pure, refreshing sugarcane juice the way nature intended.',
        'product.ginger.desc': 'Spicy ginger meets sweet sugarcane for an invigorating blend.',
        'product.lemon.desc': 'Zesty lemon adds a refreshing citrus twist to classic sugarcane.',
        'product.mint.desc': 'Cool mint creates a perfectly refreshing and soothing drink.',
        'product.passion.desc': 'Tropical passion fruit with sugarcane juice',
        'product.cucumber.desc': 'Crisp cucumber provides extra hydration and freshness.',
        
        'product.badge.new': 'New',
        'product.badge.popular': 'Popular',
        'product.badge.seasonal': 'Seasonal',
        
        // Gallery
        'gallery.title': 'Gallery',
        'gallery.subtitle': 'Our Fresh Juices',
        'gallery.description': 'See our fresh, delicious sugarcane juices in all their natural glory.',
        'gallery.tag.classic': 'Classic',
        'gallery.tag.blended': 'Blended',
        'gallery.featured': 'Featured',
        
        // Menu Page
        'menu.title': 'Our Menu',
        'menu.subtitle': 'Fresh Juices',
        'menu.description': 'All our juices are freshly pressed to order using the finest locally grown sugarcane.',
        'menu.all': 'All',
        'menu.customOrder': 'Custom Order',
        'menu.classic': 'Classic',
        'menu.blended': 'Blended',
        'menu.tropical': 'Tropical',
        
        // Footer
        'footer.brand': 'Utamu wa Miwa',
        'footer.tagline': 'Fresh Sugarcane Juice',
        'footer.description': 'Pure, fresh, and natural sugarcane juice from the heart of Zanzibar. Experience the authentic taste of miwa every sip.',
        
        'footer.quickLinks': 'Quick Links',
        'footer.products': 'Our Products',
        'footer.contact': 'Contact Us',
        
        'footer.address': 'Stone Town, Zanzibar, Tanzania',
        'footer.phone': '+255 718 622 621',
        'footer.whatsapp': 'Chat on WhatsApp',
        
        'footer.copyright': '© {year} Utamu wa Miwa. All rights reserved.',
        'footer.made': 'Made with 💚 in Zanzibar, Tanzania',
        
        // Common
        'common.order': 'Order Now',
        'common.learnMore': 'Learn More',
        'common.viewMenu': 'View Menu',
        'common.contact': 'Contact',
        'common.loading': 'Loading...',
        'common.error': 'Something went wrong',
        'common.retry': 'Retry',
        
        // About Page
        'about.hero.title': 'About Us',
        'about.hero.subtitle': 'Our Story',
        'about.hero.description': 'A humble beginning, a bold vision — bringing the purest taste of Zanzibar sugarcane juice to every corner of the island.',
        'about.story.title': 'Sweetness from the Soil',
        'about.story.p1': 'Utamu wa Miwa (meaning "Sweetness of the Cane" in Swahili) was born out of a deep love for natural, wholesome drinks. Our founder grew up watching family members press fresh cane juice in the fields of Zanzibar — it was the drink of celebration, of heat, of life.',
        'about.story.p2': 'In 2018, that family tradition became a business. Starting with one cart and one hand press in Stone Town, we began serving the freshest sugarcane juice to locals and tourists alike.',
        'about.story.p3': 'Today, Utamu wa Miwa stands for authenticity — every glass pressed fresh, every ingredient local, every customer treated like family. This is not just juice. This is Zanzibar in a cup.',
        'about.values.title': 'Our Values',
        'about.values.subtitle': 'What We Stand For',
        'about.values.freshness.title': 'Freshness First',
        'about.values.freshness.desc': 'We press every glass to order — never pre-made, always fresh.',
        'about.values.local.title': 'Local Sources',
        'about.values.local.desc': 'Sugarcane from trusted Zanzibari farmers who share our passion.',
        'about.values.hygiene.title': 'Hygiene & Safety',
        'about.values.hygiene.desc': 'Clean preparation environment, food-safe equipment, every time.',
        'about.values.community.title': 'Community Impact',
        'about.values.community.desc': 'Supporting local farmers and creating jobs in Zanzibar.',
        'about.journey.title': 'Journey',
        'about.milestones.title': 'Our Milestones',
        'about.milestone.2018': 'Started as a small cart in Stone Town, Zanzibar.',
        'about.milestone.2019': 'Expanded to 3 flavors and doubled daily sales.',
        'about.milestone.2021': 'Launched blended flavors — ginger, lemon, and mint.',
        'about.milestone.2023': 'Served 500+ happy customers monthly.',
        'about.milestone.2025': 'Launched our official online presence. Welcome!',
        'about.cta.title': 'Come Taste the Difference',
        'about.cta.description': 'Visit us in Stone Town or order on WhatsApp — freshness guaranteed.',
        
        // Contact Page
        'contact.hero.title': 'Contact',
        'contact.hero.subtitle': 'Get In Touch',
        'contact.hero.description': 'We\'d love to hear from you — orders, questions, or just a hello!',
        'contact.info.title': 'Contact Information',
        'contact.info.location': 'Location',
        'contact.info.location.address': 'Stone Town, Zanzibar, Tanzania',
        'contact.info.phone': 'Phone / WhatsApp',
        'contact.hours.title': 'Opening Hours',
        'contact.hours.monday': 'Monday – Friday',
        'contact.hours.saturday': 'Saturday',
        'contact.hours.sunday': 'Sunday',
        'contact.order.title': 'Order & Contact',
        'contact.whatsapp.chat': 'Chat on WhatsApp',
        'contact.phone.call': 'Call Us',
        'contact.direct.title': 'Reach Us Directly',
        'contact.whatsapp.title': 'WhatsApp',
        'contact.whatsapp.description': 'Tap to chat — we reply fast!',
        'contact.phone.title': 'Phone Call',
        'contact.phone.description': 'Call us anytime during opening hours',
        
        // Cart / Ordering
        'cart.title': 'Shopping Cart',
        'cart.empty': 'Your cart is empty',
        'cart.emptyDescription': 'Add some delicious juices to get started!',
        'cart.continueShopping': 'Continue Shopping',
        'cart.orderNote': 'Order Note (Optional)',
        'cart.orderNotePlaceholder': 'Special instructions or preferences...',
        'cart.deliveryInfo': 'Delivery Information',
        'cart.pickup': 'Pickup',
        'cart.delivery': 'Delivery',
        'cart.namePlaceholder': 'Your name',
        'cart.phonePlaceholder': 'Your phone number',
        'cart.addressPlaceholder': 'Delivery address',
        'cart.timePlaceholder': 'Scheduled time (e.g., 2:00 PM)',
        'cart.total': 'Total',
        'cart.clear': 'Clear Cart',
        'cart.orderWhatsApp': 'Order via WhatsApp',
        'cart.addToCart': 'Add to Cart',
        'cart.itemAdded': 'Added to cart',
        'cart.itemRemoved': 'Removed from cart',
        'cart.cartUpdated': 'Cart updated',
        
        // Pricing categories
        'price.small': 'Small Glass',
        'price.medium': 'Medium Glass', 
        'price.large': 'Large Bottle',
        'price.selectSize': 'Select Size',
        'price.from': 'From',
        'price.selectPrice': 'Select Price',
        'price.smallPrice': '500 TZS',
        'price.mediumPrice': '1,000 TZS',
        'price.largePrice': '4,000 TZS',
        'price.smallGlass': 'Small - 500 TZS',
        'price.mediumGlass': 'Medium - 1,000 TZS',
        'price.largeBottle': 'Large - 4,000 TZS',
        
        // Store Locator
        'storeLocator.hero.title': 'Find Our Stores',
        'storeLocator.hero.subtitle': 'Visit Us in Zanzibar',
        'storeLocator.hero.description': 'Discover our convenient locations across Zanzibar and enjoy fresh sugarcane juice near you.',
        'storeLocator.findNearby': 'Find Nearby Stores',
        'storeLocator.searchPlaceholder': 'Search stores by name or location...',
        'storeLocator.filter': 'Filter',
        'storeLocator.storesNearYou': 'Stores Near You',
        'storeLocator.mainStore': 'Main Store',
        'storeLocator.directions': 'Directions',
        'storeLocator.call': 'Call',
        'storeLocator.mapTitle': 'Store Locations',
        'storeLocator.resetView': 'Reset View',
        'stores.stoneTown': 'Utamu wa Miwa - Stone Town',
        'stores.stoneTown.address': 'MKwapa Street, Stone Town',
        'stores.nungwi': 'Utamu wa Miwa - Nungwi',
        'stores.nungwi.address': 'Nungwi Beach Road, Nungwi',
        'stores.paje': 'Utamu wa Miwa - Paje',
        'stores.paje.address': 'Paje Beach Road, Paje',
        'stores.kendwa': 'Utamu wa Miwa - Kendwa',
        'stores.kendwa.address': 'Kendwa Beach Road, Kendwa',
        'storeLocator.features.delivery': 'Delivery',
        'storeLocator.features.wifi': 'WiFi',
        'storeLocator.features.parking': 'Parking',
        'storeLocator.features.seating': 'Seating',
        'storeLocator.features.beach_view': 'Beach View',
        'storeLocator.features.kitesurfing_area': 'Kitesurfing Area',
        'storeLocator.features.sunset_view': 'Sunset View',
        
        // Reviews
        'reviews.hero.title': 'Customer Reviews',
        'reviews.hero.subtitle': 'What Our Customers Say',
        'reviews.hero.description': 'Read authentic reviews from our satisfied customers and share your own experience.',
        'reviews.writeReview': 'Write a Review',
        'reviews.basedOn': 'Based on',
        'reviews.reviews': 'reviews',
        'reviews.ratingDistribution': 'Rating Distribution',
        'reviews.verifiedPurchases': 'verified purchases',
        'reviews.fiveStarReviews': 'five-star reviews',
        'reviews.helpfulVotes': 'helpful votes',
        'reviews.searchPlaceholder': 'Search reviews...',
        'reviews.allRatings': 'All Ratings',
        'reviews.stars': 'stars',
        'reviews.star': 'star',
        'reviews.mostRecent': 'Most Recent',
        'reviews.mostHelpful': 'Most Helpful',
        'reviews.highestRated': 'Highest Rated',
        'reviews.customerReviews': 'Customer Reviews',
        'reviews.noReviews': 'No reviews yet',
        'reviews.beFirstToReview': 'Be the first to share your experience!',
        'reviews.writeFirstReview': 'Write the First Review'
      },
      
      sw: {
        // Navigation
        'nav.home': 'Nyumbani',
        'nav.about': 'Kuhusu Sisi',
        'nav.menu': 'Menyu Yetu',
        'nav.gallery': 'Gallery',
        'nav.storeLocator': 'Pata Maduka',
        'nav.reviews': 'Maoni',
        'nav.contact': 'Wasiliana',
        
        // Home Page
        'home.hero.title': 'Maji ya Miwa Freshi',
        'home.hero.subtitle': 'Kutoka Mwanzo wa Zanzibar',
        'home.hero.description': 'Pata ladha halisi ya maji ya miwa freshi, ya kiasili, tamu na yenye virutubisho vingi.',
        'home.hero.cta': 'Agiza Sasa',
        'home.hero.cta2': 'Ona Menyu',
        
        'home.about.title': 'Kuhusu Utamu wa Miwa',
        'home.about.description': 'Tunakuletea maji ya miwa freshi zaidi, yanayosukuliwa kila siku kutoka kwa miwa inayolimwa eneo hili. Njia zetu za kiasili zinahakikisha freshi na utamu wa kiasili.',
        'home.about.cta': 'Jifunze Zaidi',
        'home.cta.description': 'Agiza sasa kwenye WhatsApp na tutakuwa na maji freshi yako tayari!',
        'home.cta.button': 'Zungumza kwenye WhatsApp',
        
        'home.stats.customers': 'Wateja Wenye Furaha',
        'home.stats.flavors': 'Flava za Kipekee',
        'home.stats.years': 'Miaka ya Ufanisi',
        'home.stats.daily': 'Freshi Kila Siku',
        
        'home.menu.title': 'Menyu Yetu',
        
        // Why Us Section
        'home.whyUs.title': 'Kwa Nini Sisi?',
        'home.whyUs.subtitle': 'Kinachotufanya Tukupe Kipekee',
        'home.whyUs.fresh.title': '100% Freshi',
        'home.whyUs.fresh.desc': 'Imesukumwa freshi mbele yako — hakuna preservatives, hakina ladha za bandia.',
        'home.whyUs.local.title': 'Miwa ya Ndani',
        'home.whyUs.local.desc': 'Imetengenezwa moja kwa moja kwa wakulima wa Zanzibar wa karibu kwa freshi zaidi.',
        'home.whyUs.energy.title': 'Nishati ya Asili',
        'home.whyUs.energy.desc': 'Nishati kamili ya asili — sukari tupu ya miwa, hakuna kafeini.',
        'home.whyUs.love.title': 'Imetengenezwa kwa Pendo',
        'home.whyUs.love.desc': 'Kila kikombe kinatengenezwa kwa shauku na utunzaji na timu yetu ya karibu.',
        'home.cta.title': 'Umejiandaa Kwa Kunywa Kitu Freshi?',
        'home.viewFullMenu': 'Ona Menyu Kamili',
        'home.reviews.title': 'Mapitio',
        'home.reviews.subtitle': 'Wateja Wetu Wanachosema',
        'customer.name': 'bin abass',
        'about.title': 'Imezaliwa kwa Moyo wa Zanzibar',
        'about.description': 'Utamu wa Miwa ilianza kama muuzaji mdogo wa barabarani mjini Stone Town, Zanzibar. Kwa miwa freshi kutoka mashambani moja kwa moja, tunasukuma kila kikombe kwa mkono — kutoa ladha safi ya asili ambayo Wazanzibari wameipenda kwa vizazi.',
        'header.tagline': 'Freshi kutoka shambani kwa glasi',
        'nav.more': 'Zaidi',
        
        // Products
        'product.classic': 'Maji ya Miwa ya Kiasili',
        'product.ginger': 'Mchanganyiko wa Miwa na Tangawizi',
        'product.lemon': 'Mkanganyiko wa Miwa na Ndimu',
        'product.mint': 'Mchanganyiko wa Miwa na Mint',
        'product.passion': 'Mchanganyiko wa Miwa na Matunda ya Passion',
        'product.cucumber': 'Mchanganyiko wa Miwa na Tangweni',
        'product.extraIce': 'Barafu ya Ziada',
        'product.extraIce.desc': 'Barafu freshi za kuongeza uchu',
        
        'product.classic.desc': 'Maji ya miwa freshi na safi kama mungu alivyo takasifu.',
        'product.ginger.desc': 'Tangawizi kali inakutana na miwa tamu kwa mchanganyiko wa kusisimua.',
        'product.lemon.desc': 'Ndimu tamu zinaongeza mkanganyiko wa matunda freshi kwa miwa ya kiasili.',
        'product.mint.desc': 'Mint baridi inaunda kinywaji cha kusaidisha na kupumua.',
        'product.passion.desc': 'Matunda ya passion ya tropiki hutoa utamu wa kipekee kwa maji freshi yetu.',
        'product.cucumber.desc': 'Tangweni crsip hutoa maji ya ziada na freshi.',
        
        'product.badge.new': 'Mpya',
        'product.badge.popular': ' maarufu',
        'product.badge.seasonal': 'Msimu',
        
        // Gallery
        'gallery.title': 'Gallery',
        'gallery.subtitle': 'Maji Freshi Yetu',
        'gallery.description': 'Ona maji freshi na tamu ya miwa katika utukufu wao wa kiasili.',
        'gallery.tag.classic': 'Kiasili',
        'gallery.tag.blended': 'Imechanganywa',
        'gallery.featured': 'Imechaguliwa',
        
        // Menu Page
        'menu.title': 'Menyu Yetu',
        'menu.subtitle': 'Menyu ya Maji Freshi',
        'menu.description': 'Maji yote yanayotengenezwa freshi agizo — chagua ladha yako, ufurahie ubunifu.',
        'menu.customOrders': 'Maagizo maalum yanakaribishwa!',
        'menu.customOrdersDesc': 'Unataka mchanganyiko maalum? Wasiliana nasi kupitia WhatsApp',
        'menu.addons': 'Viongizo',
        'menu.addons.desc': 'Boresha kinywaji chako na hizi ziada',
        'menu.extraIce': 'Barafu ya Ziada',
        'menu.extraIce.desc': 'Ongeza barafu ya ziada kwenye kinywaji chako',
        'menu.customOrder': 'Agizo Maalum',
        'menu.classic': 'Kiasili',
        'menu.blended': 'Imechanganywa',
        'menu.tropical': 'Ya Tropiki',
        
// ... (rest of the code remains the same)
        // Footer
        'footer.brand': 'Utamu wa Miwa',
        'footer.tagline': 'Maji ya Miwa Freshi',
        'footer.description': 'Maji ya miwa safi, freshi, na ya kiasili kutoka mwanzo wa Zanzibar. Pata ladha halisi ya miwa kila kijiko.',
        
        'footer.quickLinks': 'Viunga vya Haraka',
        'footer.products': 'Bidhaa Zetu',
        'footer.contact': 'Wasiliana Nasi',
        
        'footer.address': 'Stone Town, Zanzibar, Tanzania',
        'footer.phone': '+255 718 622 621',
        'footer.whatsapp': 'Zungumza kwenye WhatsApp',
        
        'footer.copyright': '© {year} Utamu wa Miwa. Haki zote zimehifadhiwa.',
        'footer.made': 'Imetengenezwa kwa 💚 huko Zanzibar, Tanzania',
        
        // Common
        'common.order': 'Agiza Sasa',
        'common.learnMore': 'Jifunze Zaidi',
        'common.viewMenu': 'Ona Menyu',
        'common.contact': 'Wasiliana',
        'common.loading': 'Inapakia...',
        'common.error': 'Kimekosewa',
        'common.retry': 'Jaribu Tena',
        
        // About Page
        'about.hero.title': 'Kuhusu Sisi',
        'about.hero.subtitle': 'Hadithi Yetu',
        'about.hero.description': 'Mwanzo wa unyenyekevu, dhamu kubwa — kuleta ladha safi zaidi ya maji ya miwa ya Zanzibar kwa kila kona ya kisiwa.',
        'about.story.title': 'Utamu kutoka Ardhi',
        'about.story.p1': 'Utamu wa Miwa (maana yake "Utamu wa Miwa" kwa Kiswahili) ulizaliwa kwa upendo mkubwa wa vinywaji vya asili na vya afya. Mwanzishi wetu alikua akiwaona wanafamilia wakinyunyusia maji ya miwa freshi mashambani mwa Zanzibar — ndiyo kinywaji cha sherehe, cha joto, cha maisha.',
        'about.story.p2': 'Mwaka 2018, mazoezi hayo ya familia yakawa biashara. Kuanzia na gari moja na shinikizo moja la mkononi mjini Stone Town, tukaanza kutoa maji ya miwa freshi kwa wenyeji na watalii.',
        'about.story.p3': 'Leo, Utamu wa Miwa inasimamia ukweli — kila kikombe kinachosukuliwa freshi, kila kiungo cha karibu, kila mteja anaelezewa kama familia. Hii si tu maji. Hii ni Zanzibar kwenye kikombe.',
        'about.values.title': 'Thamani Zetu',
        'about.values.subtitle': 'Tutakayo Simama',
        'about.values.freshness.title': 'Freshi Kwanza',
        'about.values.freshness.desc': 'Tunasukumia kila kikombe kwa agizo — haijuiandaliwa mapema, daima ni freshi.',
        'about.values.local.title': 'Vyanzo vya Karibu',
        'about.values.local.desc': 'Miwa kutoka wakulima wa Zanzibari wanaoaminika wanaoshiriki shauku letu.',
        'about.values.hygiene.title': 'Usafi na Usalama',
        'about.values.hygiene.desc': 'Mazingira safi ya maandalizi, vifaa vya chakula salama, kila wakati.',
        'about.values.community.title': 'Athari za Jamii',
        'about.values.community.desc': 'Kuunga mkono wakulima wa karibu na kuunda ajira Zanzibar.',
        'about.journey.title': 'Safari',
        'about.milestones.title': 'Mafanikio Yetu',
        'about.milestone.2018': 'Ilianza kama gari dogo mjini Stone Town, Zanzibar.',
        'about.milestone.2019': 'Iliongeza hadi ladha 3 na kuuzuzia mara mbili kila siku.',
        'about.milestone.2021': 'Ilanzisha ladha zilizochanganywa — tangawizi, ndimu, na mint.',
        'about.milestone.2023': 'Ilitoa huduma kwa wateja 500+ wafurahi kila mwezi.',
        'about.milestone.2025': 'Ilanzisha uwepo wetu rasmi mtandaoni. Karibu!',
        'about.cta.title': 'Njoo Pata Ladha tofauti',
        'about.cta.description': 'Tembelea mjini Stone Town au agiza kwenye WhatsApp — freshi inahakikishwa.',
        
        // Contact Page
        'contact.hero.title': 'Wasiliana',
        'contact.hero.subtitle': 'Wasiliana Nasi',
        'contact.hero.description': 'Tupendezwa kusikia kutoka kwako — maagizo, maswali, au salamu tu!',
        'contact.info.title': 'Maelezo ya Wasiliana',
        'contact.info.location': 'Mahali',
        'contact.info.location.address': 'Stone Town, Zanzibar, Tanzania',
        'contact.info.phone': 'Simu / WhatsApp',
        'contact.hours.title': 'Masaa ya Ufungaji',
        'contact.hours.monday': 'Jumatatu – Ijumaa',
        'contact.hours.saturday': 'Jumamosi',
        'contact.hours.sunday': 'Jumapili',
        'contact.order.title': 'Agizo na Wasiliana',
        'contact.whatsapp.chat': 'Zungumza kwenye WhatsApp',
        'contact.phone.call': 'Pigia Simu',
        'contact.direct.title': 'Wasiliana Nasi Moja kwa Moja',
        'contact.whatsapp.title': 'WhatsApp',
        'contact.whatsapp.description': 'Gusa kuongea — tunajibu haraka!',
        'contact.phone.title': 'Simu',
        'contact.phone.description': 'Pigia simu wakati wowote masaa ya ufungaji',
        
        // Cart / Ordering
        'cart.title': 'Basketi ya Ununuzi',
        'cart.empty': 'Basketi yako ni tupu',
        'cart.emptyDescription': 'Ongeza maji tamu kuanza!',
        'cart.continueShopping': 'Endelea Kununua',
        'cart.orderNote': 'Maagizo ya Agizo (Hiari)',
        'cart.orderNotePlaceholder': 'Maagizo maalum au mapendeleo...',
        'cart.deliveryInfo': 'Maelezo ya Uwasilishaji',
        'cart.pickup': 'Chukua Mwenyewe',
        'cart.delivery': 'Uwasilishaji',
        'cart.namePlaceholder': 'Jina lako',
        'cart.phonePlaceholder': 'Namba ya simu yako',
        'cart.addressPlaceholder': 'Anwani ya uwasilishaji',
        'cart.timePlaceholder': 'Muda uliopangwa (k.m., 2:00 PM)',
        'cart.total': 'Jumla',
        'cart.clear': 'Futa Basketi',
        'cart.orderWhatsApp': 'Agiza kupitia WhatsApp',
        'cart.addToCart': 'Ongeza kwenye Basketi',
        'cart.itemAdded': 'Imeongezwa kwenye basketi',
        'cart.itemRemoved': 'Imeondolewa kwenye basketi',
        'cart.cartUpdated': 'Basketi imesasishwa',
        
        // Pricing categories
        'price.small': 'Kikombe Kidogo',
        'price.medium': 'Kikombe Kati', 
        'price.large': 'Chupa Kubwa',
        'price.selectSize': 'Chagua Ukubwa',
        'price.from': 'Kuanzia',
        'price.selectPrice': 'Chagua Bei',
        'price.smallPrice': '500 TZS',
        'price.mediumPrice': '1,000 TZS',
        'price.largePrice': '4,000 TZS',
        'price.smallGlass': 'Kidogo - 500 TZS',
        'price.mediumGlass': 'Kati - 1,000 TZS',
        'price.largeBottle': 'Kubwa - 4,000 TZS',
        
        // Store Locator
        'storeLocator.hero.title': 'Pata Maduka Yetu',
        'storeLocator.hero.subtitle': 'Tembelea Zanzibar',
        'storeLocator.hero.description': 'Gundua maduka yetu rahisi katika Zanzibar na ufurahie maji tamu karibu nawe.',
        'storeLocator.findNearby': 'Pata Maduka ya Karibu',
        'storeLocator.searchPlaceholder': 'Tafuta maduka kwa jina au mahali...',
        'storeLocator.filter': 'Chuja',
        'storeLocator.storesNearYou': 'Maduka ya Karibu',
        'storeLocator.mainStore': 'Duka Kuu',
        'storeLocator.directions': 'Mwelekeo',
        'storeLocator.call': 'Piga Simu',
        'storeLocator.mapTitle': 'Mahali pa Maduka',
        'storeLocator.resetView': 'Onyesha Upya',
        'stores.stoneTown': 'Utamu wa Miwa - Stone Town',
        'stores.stoneTown.address': 'Mtaa wa MKwapa, Stone Town',
        'stores.nungwi': 'Utamu wa Miwa - Nungwi',
        'stores.nungwi.address': 'Barabara ya Pwani ya Nungwi, Nungwi',
        'stores.paje': 'Utamu wa Miwa - Paje',
        'stores.paje.address': 'Barabara ya Pwani ya Paje, Paje',
        'stores.kendwa': 'Utamu wa Miwa - Kendwa',
        'stores.kendwa.address': 'Barabara ya Pwani ya Kendwa, Kendwa',
        'storeLocator.features.delivery': 'Uwasilishaji',
        'storeLocator.features.wifi': 'WiFi',
        'storeLocator.features.parking': 'Maegesho',
        'storeLocator.features.seating': 'Viti vya Kuketi',
        'storeLocator.features.beach_view': 'Mwonekano wa Pwani',
        'storeLocator.features.kitesurfing_area': 'Eneo la Kitesurfing',
        'storeLocator.features.sunset_view': 'Mwonekano wa Jua Kuchwa',
        
        // Reviews
        'reviews.hero.title': 'Maoni ya Wateja',
        'reviews.hero.subtitle': 'Wateja Wanachosema',
        'reviews.hero.description': 'Soma maoni halisi kutoka kwa wateja wetu waliolala na ushiriki uzoefu wako mwenyewe.',
        'reviews.writeReview': 'Andika Maoni',
        'reviews.basedOn': 'Kulingana na',
        'reviews.reviews': 'maoni',
        'reviews.ratingDistribution': 'Utambulisho wa Rating',
        'reviews.verifiedPurchases': 'ununuzi uliothibitishwa',
        'reviews.fiveStarReviews': 'maoni ya nyota tano',
        'reviews.helpfulVotes': 'kura za usaidizi',
        'reviews.searchPlaceholder': 'Tafuta maoni...',
        'reviews.allRatings': 'Rating Zote',
        'reviews.stars': 'nyota',
        'reviews.star': 'nyota',
        'reviews.mostRecent': 'Hivi Karibuni Zaidi',
        'reviews.mostHelpful': 'Zisaidizo Zaidi',
        'reviews.highestRated': 'Yenye Rating ya Juu',
        'reviews.customerReviews': 'Maoni ya Wateja',
        'reviews.noReviews': 'Hakuna maoni bado',
        'reviews.beFirstToReview': 'Kuwa wa kwanza kushiriki uzoefu wako!',
        'reviews.writeFirstReview': 'Andika Maoni ya Kwanza'
      },
      
      it: {
        // Navigation
        'nav.home': 'Home',
        'nav.about': 'Chi Siamo',
        'nav.menu': 'Il Nostro Menu',
        'nav.gallery': 'Galleria',
        'nav.storeLocator': 'Trova Negozi',
        'nav.reviews': 'Recensioni',
        'nav.contact': 'Contatti',
        
        // Home Page
        'home.hero.title': 'Succo di Canna da Zucchero Fresco',
        'home.hero.subtitle': 'Dal Cuore di Zanzibar',
        'home.hero.description': 'Sperimenta il gusto autentico del puro succo di canna da zucchero fresco - naturalmente dolce, rinfrescante e pieno di nutrienti.',
        'home.hero.cta': 'Ordina Ora',
        'home.hero.cta2': 'Vedi Menu',
        
        'home.about.title': 'Informazioni su Utamu wa Miwa',
        'home.about.description': 'Ti portiamo il succo di canna da zucchero più fresco, spremuto giornalmente da canna da zucchero coltivata localmente. I nostri metodi tradizionali garantiscono massima freschezza e dolcezza naturale.',
        'home.about.cta': 'Scopri di Più',
        'home.cta.description': 'Ordina ora su WhatsApp e avremo il tuo succo fresco pronto per te!',
        'home.cta.button': 'Chatta su WhatsApp',
        
        'home.stats.customers': 'Clienti Felici',
        'home.stats.flavors': 'Gusti Unici',
        'home.stats.years': 'Anni di Eccellenza',
        'home.stats.daily': 'Fresco Ogni Giorno',
        
        'home.menu.title': 'Il Nostro Menu',
        
        // Why Us Section
        'home.whyUs.title': 'Perché Noi?',
        'home.whyUs.subtitle': 'Ci Rende Speciali',
        'home.whyUs.fresh.title': '100% Fresco',
        'home.whyUs.fresh.desc': 'Spremuto fresco davanti a te — nessun conservante, nessun sapore artificiale.',
        'home.whyUs.local.title': 'Canna da Zucchero Locale',
        'home.whyUs.local.desc': 'Proveniente direttamente da agricoltori zanzibaresi locali per massima freschezza.',
        'home.whyUs.energy.title': 'Energia Naturale',
        'home.whyUs.energy.desc': 'Il perfetto boost di energia naturale — zucchero di canna puro, nessuna caffeina.',
        'home.whyUs.love.title': 'Fatto con Amore',
        'home.whyUs.love.desc': 'Ogni bicchiere preparato con passione e cura dal nostro team locale.',
        'home.cta.title': 'Pronto per un Sorso Rinfrescante?',
        'home.viewFullMenu': 'Vedi Menu Completo',
        'home.reviews.title': 'Recensioni',
        'home.reviews.subtitle': 'Dicono di Noi i Clienti',
        'customer.name': 'bin abass',
        'about.title': 'Nato dal Cuore di Zanzibar',
        'about.description': 'Utamu wa Miwa è iniziato come piccolo venditore ambulante a Stone Town, Zanzibar. Con canna da zucchero fresca proveniente direttamente dalle fattorie locali, pressiamo ogni bicchiere a mano — offrendo il puro gusto naturale che gli zanzibaresi amano da generazioni.',
        'header.tagline': 'Fresco dalla fattoria al bicchiere',
        'nav.more': 'Altro',
        
        // Products
        'product.classic': 'Succo di Canna da Zucchero Classico',
        'product.ginger': 'Mix di Canna da Zucchero e Zenzero',
        'product.lemon': 'Twist di Canna da Zucchero al Limone',
        'product.mint': 'Twist di Canna da Zucchero alla Menta',
        'product.passion': 'Twist di Canna da Zucchero alla Frutta della Passione',
        'product.cucumber': 'Twist di Canna da Zucchero al Cetriolo',
        'product.extraIce': 'Ghiaccio Extra',
        'product.extraIce.desc': 'Ghiaccio fresco per extra rinfrescamento',
        
        'product.classic.desc': 'Puro succo di canna da zucchero rinfrescante come la natura lo ha inteso.',
        'product.ginger.desc': 'Lo zenzero piccante incontra la dolce canna da zucchero per un mix energizzante.',
        'product.lemon.desc': 'Il limone agrumato aggiunge un twist rinfrescante al classico succo di canna.',
        'product.mint.desc': 'La menta fresca crea una bevanda perfettamente rinfrescante e rilassante.',
        'product.passion.desc': 'La frutta della passione tropicale aggiunge dolcezza esotica al nostro succo fresco.',
        'product.cucumber.desc': 'Il cetriolo croccante fornisce idratazione e freschezza extra.',
        
        'product.badge.new': 'Nuovo',
        'product.badge.popular': 'Popolare',
        'product.badge.seasonal': 'Stagionale',
        
        // Gallery
        'gallery.title': 'Galleria',
        'gallery.subtitle': 'I Nostri Succhi Freschi',
        'gallery.description': 'Vedi i nostri succhi di canna da zucchero freschi e deliziosi in tutta la loro gloria naturale.',
        'gallery.tag.classic': 'Classico',
        'gallery.tag.blended': 'Mixato',
        'gallery.featured': 'In Evidenza',
        
        // Menu Page
        'menu.title': 'Il Nostro Menu',
        'menu.subtitle': 'Succhi Freschi',
        'menu.description': 'Tutti i nostri succhi sono spremuti freschi su ordinazione utilizzando la migliore canna da zucchero coltivata localmente.',
        'menu.all': 'Tutti',
        'menu.customOrders': 'Ordini personalizzati benvenuti!',
        'menu.customOrdersDesc': 'Vuoi un mix speciale? Contattaci su WhatsApp',
        'menu.addons': 'Aggiunte',
        'menu.addons.desc': 'Migliora la tua bevanda con questi extra',
        'menu.customOrder': 'Ordine Personalizzato',
        'menu.classic': 'Classico',
        'menu.blended': 'Mixato',
        'menu.tropical': 'Tropicale',
        
        // Footer
        'footer.brand': 'Utamu wa Miwa',
        'footer.tagline': 'Succo di Canna da Zucchero Fresco',
        'footer.description': 'Succo di canna da zucchero puro, fresco e naturale dal cuore di Zanzibar. Sperimenta il gusto autentico della miwa a ogni sorso.',
        
        'footer.quickLinks': 'Link Rapidi',
        'footer.products': 'I Nostri Prodotti',
        'footer.contact': 'Contattaci',
        
        'footer.address': 'Stone Town, Zanzibar, Tanzania',
        'footer.phone': '+255 718 622 621',
        'footer.whatsapp': 'Chatta su WhatsApp',
        
        'footer.copyright': '© {year} Utamu wa Miwa. Tutti i diritti riservati.',
        'footer.made': 'Fatto con 💚 a Zanzibar, Tanzania',
        
        // Common
        'common.order': 'Ordina Ora',
        'common.learnMore': 'Scopri di Più',
        'common.viewMenu': 'Vedi Menu',
        'common.contact': 'Contatti',
        'common.loading': 'Caricamento...',
        'common.error': 'Qualcosa è andato storto',
        'common.retry': 'Riprova',
        
        // About Page
        'about.hero.title': 'Chi Siamo',
        'about.hero.subtitle': 'La Nostra Storia',
        'about.hero.description': 'Un inizio umile, una visione audace — portare il gusto più puro del succo di canna da zucchero di Zanzibar in ogni angolo dell\'isola.',
        'about.story.title': 'Dolcezza dalla Terra',
        'about.story.p1': 'Utamu wa Miwa (che significa "Dolcezza della Canna" in swahili) è nato da un profondo amore per le bevande naturali e salutari. Il nostro fondatore è cresciuto guardando i membri della famiglia spremere succo di canna da zucchero fresco nei campi di Zanzibar — era la bevanda della celebrazione, del calore, della vita.',
        'about.story.p2': 'Nel 2018, quella tradizione familiare è diventata un\'attività. Partendo con un carrello e una pressa a mano a Stone Town, abbiamo iniziato a servire il succo di canna da zucchero più fresco a locali e turisti.',
        'about.story.p3': 'Oggi, Utamu wa Miwa rappresenta l\'autenticità — ogni bicchiere spremuto fresco, ogni ingrediente locale, ogni cliente trattato come famiglia. Questo non è solo succo. Questo è Zanzibar in un bicchiere.',
        'about.values.title': 'I Nostri Valori',
        'about.values.subtitle': 'Cosa Rappresentiamo',
        'about.values.freshness.title': 'Freschezza Prima di Tutto',
        'about.values.freshness.desc': 'Spremiamo ogni bicchiere su ordinazione — mai pre-preparato, sempre fresco.',
        'about.values.local.title': 'Fonti Locali',
        'about.values.local.desc': 'Canna da zucchero da agricoltori fidati di Zanzibar che condividono la nostra passione.',
        'about.values.hygiene.title': 'Igiene e Sicurezza',
        'about.values.hygiene.desc': 'Ambiente di preparazione pulito, attrezzature sicure per alimenti, ogni volta.',
        'about.values.community.title': 'Impatto sulla Comunità',
        'about.values.community.desc': 'Supportando gli agricoltori locali e creando posti di lavoro a Zanzibar.',
        'about.journey.title': 'Viaggio',
        'about.milestones.title': 'Le Nostre Tappe',
        'about.milestone.2018': 'Iniziato come piccolo carrello a Stone Town, Zanzibar.',
        'about.milestone.2019': 'Espanso a 3 gusti e raddoppiato le vendite giornaliere.',
        'about.milestone.2021': 'Lanciati gusti misti — zenzero, limone e menta.',
        'about.milestone.2023': 'Servito 500+ clienti felici mensilmente.',
        'about.milestone.2025': 'Lanciata la nostra presenza online ufficiale. Benvenuto!',
        'about.cta.title': 'Vieni a Assaporare la Differenza',
        'about.cta.description': 'Visitaci a Stone Town o ordina su WhatsApp — freschezza garantita.',
        
        // Contact Page
        'contact.hero.title': 'Contatti',
        'contact.hero.subtitle': 'Contattaci',
        'contact.hero.description': 'Ci piacerebbe sentirti — ordini, domande, o solo un ciao!',
        'contact.info.title': 'Informazioni di Contatto',
        'contact.info.location': 'Posizione',
        'contact.info.location.address': 'Stone Town, Zanzibar, Tanzania',
        'contact.info.phone': 'Telefono / WhatsApp',
        'contact.hours.title': 'Orari di Apertura',
        'contact.hours.monday': 'Lunedì – Venerdì',
        'contact.hours.saturday': 'Sabato',
        'contact.hours.sunday': 'Domenica',
        'contact.order.title': 'Ordina e Contatta',
        'contact.whatsapp.chat': 'Chatta su WhatsApp',
        'contact.phone.call': 'Chiama',
        'contact.direct.title': 'Contattaci Direttamente',
        'contact.whatsapp.title': 'WhatsApp',
        'contact.whatsapp.description': 'Tocca per chattare — rispondiamo velocemente!',
        'contact.phone.title': 'Chiamata Telefonica',
        'contact.phone.description': 'Chiamaci anytime durante gli orari di apertura',
        
        // Cart / Ordering
        'cart.title': 'Carrello della Spesa',
        'cart.empty': 'Il tuo carrello è vuoto',
        'cart.emptyDescription': 'Aggiungi succhi deliziosi per iniziare!',
        'cart.continueShopping': 'Continua lo Shopping',
        'cart.orderNote': 'Note dell\'Ordine (Opzionale)',
        'cart.orderNotePlaceholder': 'Istruzioni speciali o preferenze...',
        'cart.deliveryInfo': 'Informazioni di Consegna',
        'cart.pickup': 'Ritiro',
        'cart.delivery': 'Consegna',
        'cart.namePlaceholder': 'Il tuo nome',
        'cart.phonePlaceholder': 'Il tuo numero di telefono',
        'cart.addressPlaceholder': 'Indirizzo di consegna',
        'cart.timePlaceholder': 'Orario programmato (es., 2:00 PM)',
        'cart.total': 'Totale',
        'cart.clear': 'Svuota Carrello',
        'cart.orderWhatsApp': 'Ordina via WhatsApp',
        'cart.addToCart': 'Aggiungi al Carrello',
        'cart.itemAdded': 'Aggiunto al carrello',
        'cart.itemRemoved': 'Rimosso dal carrello',
        'cart.cartUpdated': 'Carrello aggiornato',
        
        // Pricing categories
        'price.small': 'Bicchiere Piccolo',
        'price.medium': 'Bicchiere Medio', 
        'price.large': 'Bottiglia Grande',
        'price.selectSize': 'Seleziona Dimensione',
        'price.from': 'Da',
        'price.selectPrice': 'Seleziona Prezzo',
        'price.smallPrice': '500 TZS',
        'price.mediumPrice': '1,000 TZS',
        'price.largePrice': '4,000 TZS',
        'price.smallGlass': 'Piccolo - 500 TZS',
        'price.mediumGlass': 'Medio - 1,000 TZS',
        'price.largeBottle': 'Grande - 4,000 TZS',
        
        // Store Locator
        'storeLocator.hero.title': 'Trova i Nostri Negozi',
        'storeLocator.hero.subtitle': 'Visitaci a Zanzibar',
        'storeLocator.hero.description': 'Scopri le nostre comode località a Zanzibar e goditi succo di canna da zucchero fresco vicino a te.',
        'storeLocator.findNearby': 'Trova Negozi Vicini',
        'storeLocator.searchPlaceholder': 'Cerca negozi per nome o località...',
        'storeLocator.filter': 'Filtra',
        'storeLocator.storesNearYou': 'Negozi Vicino a Te',
        'storeLocator.mainStore': 'Negozio Principale',
        'storeLocator.directions': 'Indicazioni',
        'storeLocator.call': 'Chiama',
        'storeLocator.mapTitle': 'Località dei Negozi',
        'storeLocator.resetView': 'Reimposta Vista',
        'stores.stoneTown': 'Utamu wa Miwa - Stone Town',
        'stores.stoneTown.address': 'Via MKwapa, Stone Town',
        'stores.nungwi': 'Utamu wa Miwa - Nungwi',
        'stores.nungwi.address': 'Via Spiaggia Nungwi, Nungwi',
        'stores.paje': 'Utamu wa Miwa - Paje',
        'stores.paje.address': 'Via Spiaggia Paje, Paje',
        'stores.kendwa': 'Utamu wa Miwa - Kendwa',
        'stores.kendwa.address': 'Via Spiaggia Kendwa, Kendwa',
        'storeLocator.features.delivery': 'Consegna',
        'storeLocator.features.wifi': 'WiFi',
        'storeLocator.features.parking': 'Parcheggio',
        'storeLocator.features.seating': 'Posti a Sedere',
        'storeLocator.features.beach_view': 'Vista Mare',
        'storeLocator.features.kitesurfing_area': 'Area Kitesurf',
        'storeLocator.features.sunset_view': 'Vista Tramonto',
        
        // Reviews
        'reviews.hero.title': 'Recensioni dei Clienti',
        'reviews.hero.subtitle': 'Dicono di Noi',
        'reviews.hero.description': 'Leggi recensioni autentiche dai nostri clienti soddisfatti e condividi la tua esperienza.',
        'reviews.writeReview': 'Scrivi una Recensione',
        'reviews.basedOn': 'Basato su',
        'reviews.reviews': 'recensioni',
        'reviews.ratingDistribution': 'Distribuzione Valutazioni',
        'reviews.verifiedPurchases': 'acquisti verificati',
        'reviews.fiveStarReviews': 'recensioni a 5 stelle',
        'reviews.helpfulVotes': 'voti utili',
        'reviews.searchPlaceholder': 'Cerca recensioni...',
        'reviews.allRatings': 'Tutte le Valutazioni',
        'reviews.stars': 'stelle',
        'reviews.star': 'stella',
        'reviews.mostRecent': 'Più Recenti',
        'reviews.mostHelpful': 'Più Utili',
        'reviews.highestRated': 'Più Valutate',
        'reviews.customerReviews': 'Recensioni dei Clienti',
        'reviews.noReviews': 'Nessuna recensione ancora',
        'reviews.beFirstToReview': 'Sii il primo a condividere la tua esperienza!',
        'reviews.writeFirstReview': 'Scrivi la Prima Recensione'
      }
    }
    
    return translations[language]?.[key] || key
  }

  const value = {
    language,
    setLanguage,
    t,
    // Available languages
    languages: [
      { code: 'en', name: 'English', flag: '🇬🇧' },
      { code: 'sw', name: 'Kiswahili', flag: '🇹🇿' },
      { code: 'it', name: 'Italiano', flag: '🇮🇹' },
    ],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageProvider;
